INIT_MANAGER_DEFAULT:forcevariable = "systemd"
IMAGE_FEATURES:remove = "ssh-server-dropbear"
IMAGE_INSTALL:append = " libiio-dev \
                         libiio \
                         libiio-tests \
                         libiio-iiod \
                         libcsp \
                         libcsp-dev \
                         libcsp-examples \
                         dtoverlay \
                         usb-ether \
                         fsatutils \
                         can-utils \
                         i2c-tools \
                         mmc-utils \
                         nlohmann-json-dev \
                         fsat2-engine \
                         libgpiod-tools \
                         sqlite3"

IMAGE_INSTALL:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'fpga-overlay', ' zed-bitstream', '', d)}"
IMAGE_INSTALL:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'fpga-overlay', ' rad-test-bitstream', '', d)}"

IMAGE_BOOT_FILES:zynq = "BOOT.BIN boot.scr uImage"

PARALLEL_MAKE ?= "-j 10"
BB_NUMBER_THREADS ?= "12"

DL_DIR = "/home/petalinux/sstate/downloads"
SSTATE_DIR = "/home/petalinux/sstate/sstate-cache/arm"
